---
version: '2.1'
volumes:
  coredns-data:
services:
  coredns:
    build: .
    dns:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: host
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - "coredns-data:/data"
